name: causal_alignment_env
dependencies:
  - python=3.11
  - r-base
  - r-essentials
  - jupyter
  - pip
  - pip:
    - transformers
    - datasets
    - transformer_lens
    - huggingface_hub
    - ipython
    - jaxtyping
    - torchtyping
    - tqdm
    - matplotlib
    - nbformat
    - plotly
variables: